---
title: "Untitled"
output: html_document
date: "2024-09-18"
---

/home/jtimm/Insync/jay.timm01@gmail.com/Google Drive - Shared with me/UNM - LLM Exploration/assisted_evaluation/process-evaluations/processed-outputs/

```{r}
## INTROS --
base_path <- '/home/jtimm/Insync/jay.timm01@gmail.com/Google Drive - Shared with me/UNM - LLM Exploration/assisted_evaluation/'
# Directories -- 
sf_lex_dir <- paste0(base_path, 'lexical-resources/sf_lexical_resources/')
lex_dir <- paste0(base_path, 'lexical-resources/')
output_dir <- paste0(base_path, 'process-evaluations/processed-outputs/')
freqs <- readRDS(paste0(output_dir, 'descriptors.rds'))

sms <- readRDS(paste0(lex_dir, 'sensorimotor_norms/sensorimotor_norms_raw.rds'))
```



```{r}
library(dplyr)

freqs0 <- freqs |> mutate(id = value) |> tidyr::separate_rows(value, sep = '_')

sms0 <- sms |> tidyr::pivot_wider(id_cols = c(word), 
                                  values_from = value, 
                                  names_from = data)  |>
  tidyr::pivot_longer(cols = c(concreteness:valence)) |>
  group_by(name) |>
  mutate(value_normed = (value - min(value, na.rm = TRUE)) / 
                (max(value, na.rm = TRUE) - min(value, na.rm = TRUE)),
         value_normed = round(value_normed, 3)) |>
  ungroup() |>
  tidyr::pivot_wider(id_cols = word, values_from = value_normed, names_from = name) |>
  rename(DescriptorName = word)

forms <- unique(sms0$DescriptorName)

sms1 <- sms0 |>
  tidyr::pivot_longer(cols = c(concreteness:valence)) |>
  rename(score = value) |>
  filter(!is.na(score)) |> 
  mutate(type = 'original')

## saveRDS(sms1, paste0(lex_dir, 'sensorimotor_norms/sensorimotor_norms.rds'))
```


## Regression/imputation


### Load SF-ada embeddings

```{r}
embedding_matrix <- readRDS("~/Insync/jay.timm01@gmail.com/Google Drive - Shared with me/UNM - LLM Exploration/assisted_evaluation/llm_description/llm_description_embedding/narratives/average_narratives.rds")

dts0 <- data.table::as.data.table(embedding_matrix)
dts0$DescriptorName <- tolower(rownames(embedding_matrix))
```


```{r}
## embedding_matrix  <- w2v_embs2[[1]]
```



### Train/test

```{r}
norms_list <- c(
  "concreteness",
  #"imageability",
  "lanc_auditory",
  "lanc_foot_leg",
  "lanc_gustatory",
  "lanc_hand_arm",
  "lanc_haptic",
  "lanc_head",
  "lanc_interoceptive",
  "lanc_mouth",
  "lanc_olfactory",
  "lanc_torso",
  "lanc_visual",
  "age_acquisition",
  "arousal",
  "dominance",
  "valence"
)

```


>>>>\




```{r}
new_vals_df <- list()

for(i in 1:length(norms_list)) {
  nn <- norms_list[i]  # nn <- 'concreteness'
  
  # Filter rows where the column specified by nn is not NA and select DescriptorName and the nn column
  normy <- sms0 %>%
    filter(!is.na(!!sym(nn)), DescriptorName %in% dts0$DescriptorName) %>%
    select(DescriptorName, !!sym(nn))
  
  # Rename the column dynamically
  colnames(normy)[2] <- nn
  
  # Subset and reorder the embeddings
  embedding_matrix.nn <- embedding_matrix[rownames(embedding_matrix) %in% normy$DescriptorName, ]
  embedding_matrix.nn <- embedding_matrix.nn[match(normy$DescriptorName, rownames(embedding_matrix.nn)), ]
  
  embedding_matrix.test <- embedding_matrix[!rownames(embedding_matrix) %in% normy$DescriptorName, ]
  
  tt <- data.frame(rownames(embedding_matrix),
                   !rownames(embedding_matrix) %in% normy$DescriptorName)
  # Convert to DMatrix
  dtrain <- xgboost::xgb.DMatrix(data = embedding_matrix.nn, label = normy[[nn]])
  
  # Adjusted XGBoost parameters
  params <- list(
    objective = "reg:squarederror",
    eta = 0.05,                      # Reduced learning rate
    max_depth = 3,                   # Reduced tree depth
    subsample = 0.5,                 # Reduced subsample ratio
    colsample_bytree = 0.5,          # Reduced feature subsample ratio
    lambda = 1,                      # Increased L2 regularization
    alpha = 1                        # Increased L1 regularization
  )
  
  # Train the model using cross-validation
  xgb_model_cv <- xgboost::xgb.cv(
    params = params,
    data = dtrain,
    nrounds = 200,                   # Increased number of rounds
    nfold = 5,
    missing = NA,
    early_stopping_rounds = 20,      # Increased early stopping rounds
    verbose = TRUE
  )
  
  # Get the best number of boosting rounds
  best_nrounds <- xgb_model_cv$best_iteration
  
  # Train final model using the best number of rounds
  final_model <- xgboost::xgb.train(
    params = params,
    data = dtrain,
    nrounds = best_nrounds
  )
  
  # Predict on new data
  dtest <- xgboost::xgb.DMatrix(data = embedding_matrix.test)
  
  # Make predictions on the test data
  predictions <- data.frame(
    DescriptorName = rownames(embedding_matrix.test),
    name = nn,
    score = predict(final_model, dtest)
  )
  
  new_vals_df[[i]] <- predictions
}

df <- data.table::rbindlist(new_vals_df)
df$type <- 'predicted'
```


```{r}
final <- rbind(df, sms1) |> arrange(DescriptorName) |> 
  mutate(score = round(score, 3)) |> 
  filter(DescriptorName %in% rownames(embedding_matrix), name != 'imageability')

saveRDS(final, paste0(lex_dir, 'sensorimotor_norms/sensorimotor_norms.rds'))
```








```{r fig.height=8}
xx <- c('aloe vera',
        'perfumey',
        'active yeast',
        'zest',
        'wine',
        'bitter',
        'graham cracker',
        'black currant')


library(ggplot2)
ggplot(data = final |> filter(DescriptorName %in% xx),
       aes(x = name,
           y = score,
           fill = name)) +
  
        geom_bar(stat="identity")+
        coord_polar() +
  
  facet_wrap(~DescriptorName, nrow = 2) +
  theme(legend.position="none") +
  ggtitle('Lancaster Sensorimotor Norms')
```




